const TR_UPGS = {
	1: { cost: new ExpantaNum(50), desc: "Increase Time Cube gain by 10% for each Rank or Tier." },
	2: { cost: new ExpantaNum(300), desc: "Time goes by (log(n+1)) times faster, where n is your Time Cubes." },
	3: { cost: new ExpantaNum(1000), desc: "The Rank requirement formula is 10% slower." },
	4: { cost: new ExpantaNum(2500), desc: "Time Cube gain is increased by 33% for every OoM of Rockets (softcaps after a while)." },
	5: { cost: new ExpantaNum(15000), desc: "Rocket Fuel is 10% stronger." },
	6: { cost: new ExpantaNum(25000), desc: "Scrap & Intelligence gain are increased by 10% for every OoM of Time Cubes." },
	7: { cost: new ExpantaNum(40000), desc: "Time goes by 5% faster for every achievement gotten." },
	8: { cost: new ExpantaNum(75000), desc: "Rankbot's interval boosts its magnitude." },
	9: { cost: new ExpantaNum(1.2e5), desc: "Tierbot's interval boosts its magnitude, but not as strongly as the previous upgrade." },
	10: { cost: new ExpantaNum(2e5), desc: "Rocket gain is increased by 10% for every OoM of Time Cubes (softcaps after a while)." },
	11: { cost: new ExpantaNum(1e60), desc: "Time Cubes and Dark Flow boost each other, and Scaled Rank scaling starts 10 Ranks later." },
	12: { cost: new ExpantaNum(1e70), desc: "Each component of The Dark Circle boosts Dark Flow, and Scaled Tier scaling starts 2 Tiers later." },
	13: { cost: new ExpantaNum(1e105), desc: "Each component of The Dark Circle boosts Pathogen Upgrade efficiency." },
	14: { cost: new ExpantaNum(1e115), desc: "Tiers do not reset anything, Scaled Tier scaling starts later based on your Dark Cores, and Tiers boost Cadaver gain." },
	15: { cost: new ExpantaNum(4.56e123), desc: "Scaled Rank scaling starts 32 Ranks later, and all effects of The Dark Circle are stronger based on your Dark Cores." },
	16: { cost: new ExpantaNum(4), desc: "Time Cube gain & Coal gain boost each other." },
	17: { cost: new ExpantaNum(10), desc: "Blue Flame is stronger based on your Time Cubes, and getting Rocket Fuel does not reset anything." },
	18: { cost: new ExpantaNum(500), desc: "Time goes by faster based on your Rank Cheapeners." },
	19: { cost: new ExpantaNum(1e5), desc: "Rank Cheapener-bot's interval boosts its magnitude." },
	20: { cost: new ExpantaNum(1.5e5), desc: "Rank Cheapeners also cheapen Tiers, but at a very reduced rate." },
	21: { cost: new ExpantaNum(1e13), desc: "Automate The Furnace." },
	22: { cost: new ExpantaNum(1e24), desc: "Rank Cheapeners are stronger based on your Cadavers (not retroactive)." },
	23: { cost: new ExpantaNum(2.5e26), desc: "Blue Flame boosts Time Speed." },
	24: { cost: new ExpantaNum(1.2e30), desc: "The 'Time Doesnt Exist' achievement effect is 40% stronger." },
	25: { cost: new ExpantaNum(1e34), desc: "Double the Coal effect." },
	26: { cost: new ExpantaNum(1e96), desc: "Dark Flow boosts Blue Flame." },
	27: { cost: new ExpantaNum(1e100), desc: "Coal boosts Pathogen Upgrade Power." },
	28: { cost: new ExpantaNum(1e136), desc: "Coal boosts Rocket gain." },
	29: { cost: new ExpantaNum(1e150), desc: "Dark Fluid & Rockets boost Rocket gain." },
	30: { cost: new ExpantaNum(1e152), desc: "Time Speed is raised to the power of (x+1), where x is based on your Pathogens." },
}
const TR_UPG_AMT = Object.keys(TR_UPGS).length
