function updateTempEarlyGame() {
	// Acceleration
	tmp.acc = new ExpantaNum(0.1)
	if (tmp.modes.hard.active) tmp.acc = tmp.acc.div(3)
	if (player.rank.gt(2)) tmp.acc = tmp.acc.times(tmp.r2)
	if (player.rank.gt(3)) tmp.acc = tmp.acc.times(2)
	if (player.tier.gt(1) && player.rank.gte(3)) tmp.acc = tmp.acc.times(2)
	if (player.rank.gt(4)) tmp.acc = tmp.acc.times(tmp.r4)
	if (player.rank.gt(5)) tmp.acc = tmp.acc.times(tmp.r5)
	if (player.rank.gt(10)) tmp.acc = tmp.acc.times(2)
	if (player.tier.gt(3)) tmp.acc = tmp.acc.times(3)
	if (player.rank.gt(14)) tmp.acc = tmp.acc.times(tmp.r14)
	if (player.rank.gt(15)) tmp.acc = tmp.acc.times(4)
	if (player.tier.gt(5)) tmp.acc = tmp.acc.times(5)
	if (player.rank.gt(25)) tmp.acc = tmp.acc.times(10)
	if (player.rank.gt(50)) tmp.acc = tmp.acc.times(15)
	if (player.tier.gt(8)) tmp.acc = tmp.acc.times(10)
	if (player.tier.gt(10)) tmp.acc = tmp.acc.times(15)
	if (player.rank.gt(75)) tmp.acc = tmp.acc.times(25)
	if (player.tier.gt(15)) tmp.acc = tmp.acc.times(25)
	if (tmp.ach) if (tmp.ach[12].has) tmp.acc = tmp.acc.times(1.1)
	if (tmp.ach) if (tmp.ach[23].has) tmp.acc = tmp.acc.times(1.2)
	if (tmp.ach) if (tmp.ach[14].has) tmp.acc = tmp.acc.times(1.5)
	if (tmp.ach) if (tmp.ach[32].has) tmp.acc = tmp.acc.times(1.8)
	if (tmp.ach) if (tmp.ach[35].has) tmp.acc = tmp.acc.times(1.8)
	if (tmp.rockets) tmp.acc = tmp.acc.times(tmp.rockets.accPow)

	// Max Velocity
	tmp.maxVel = new ExpantaNum(1)
	if (player.rank.gt(1)) tmp.maxVel = tmp.maxVel.plus(1)
	if (tmp.modes.hard.active) tmp.maxVel = tmp.maxVel.div(2)
	if (player.rank.gt(2)) tmp.maxVel = tmp.maxVel.times(tmp.r2)
	if (player.tier.gt(1) && player.rank.gte(3)) tmp.maxVel = tmp.maxVel.times(5)
	if (player.rank.gt(4)) tmp.maxVel = tmp.maxVel.times(tmp.r4)
	if (player.rank.gt(5)) tmp.maxVel = tmp.maxVel.times(tmp.r5)
	if (player.rank.gt(8)) tmp.maxVel = tmp.maxVel.times(tmp.r8)
	if (player.rank.gt(14)) tmp.maxVel = tmp.maxVel.times(tmp.r14)
	if (player.rank.gt(55)) tmp.maxVel = tmp.maxVel.times(tmp.r55)
	if (player.tier.gt(9)) tmp.maxVel = tmp.maxVel.times(tmp.t9)
	if (tmp.pathogens && player.pathogens.unl) tmp.maxVel = tmp.maxVel.times(tmp.pathogens[4].eff)
	if (tmp.ach) if (tmp.ach[21].has) tmp.maxVel = tmp.maxVel.times(1.1)
	if (tmp.ach) if (tmp.ach[14].has) tmp.maxVel = tmp.maxVel.times(1.5)
	if (tmp.ach) if (tmp.ach[24].has) tmp.maxVel = tmp.maxVel.times(1.25)
	if (tmp.ach) if (tmp.ach[41].has) tmp.maxVel = tmp.maxVel.times(1.5)
	if (tmp.ach) if (tmp.ach[51].has) tmp.maxVel = tmp.maxVel.times(1.5)
	if (tmp.ach) if (tmp.ach[61].has) tmp.maxVel = tmp.maxVel.times(1.6)
	if (tmp.rockets) tmp.maxVel = tmp.maxVel.times(tmp.rockets.mvPow)
}